matrix:
  include:
  - language: python
    python: 3.7
    before_script:
    - cd python
    - pip install pipenv
    - pipenv install --dev
    script:
    - pipenv run pytest
before_install:
- openssl aes-256-cbc -K $encrypted_823a8aeaad18_key -iv $encrypted_823a8aeaad18_iv
  -in secrets.sh.enc -out secrets.sh -d
- source environment.sh
