matrix:
  include:
    - language: python
      name: test_cli
      stage: test
      python: 3.7
      install:
        # START TESTING THE CLI
        - cd cli
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run pytest
        # END TESTING THE CLI
    - language: python
      name: test_clients
      stage: test
      python: 3.7
      install:
        - pip install ./cli
        - onshape-clients install
      script:
        - onshape-clients test
    - language: python
      name: lint_clients
      stage: test
      python: 3.7
      install:
        - pip install ./cli
      script:
        - onshape-clients lint
    - language: python
      name: deploy_clients
      stage: deploy
      python: 3.7
      install:
        - nvm install 12
        - pip install ./cli
        - which onshape-clients
        - npm install .
      script:
        - npx semantic-release
stages:
  - test
  - deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_823a8aeaad18_key -iv $encrypted_823a8aeaad18_iv
    -in secrets.sh.enc -out secrets.sh -d
  - source environment.sh
