matrix:
  include:
    - name: test_cli
      stage: test
      install:
        # START TESTING THE CLI
        - cd cli
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run pytest
        # END TESTING THE CLI
    - name: test_clients
      stage: test
      script:
        - onshape-clients setup
        - PATH=$PATH:~/bin/openapitools/
        - onshape-clients -c go generate
        - onshape-clients install
        - onshape-clients test
    - name: lint_clients
      stage: test
      script:
        - onshape-clients lint
    - name: deploy_clients
      stage: deploy
      install:
        - onshape-clients setup
        - PATH=$PATH:~/bin/openapitools/
        - onshape-clients -c go generate
        - nvm install 12
        - npm install .
      script:
        - npx semantic-release
stages:
  - test
  - deploy
language: python
python: 3.7
before_install:
  - openssl aes-256-cbc -K $encrypted_823a8aeaad18_key -iv $encrypted_823a8aeaad18_iv
    -in secrets.sh.enc -out secrets.sh -d
  - source environment.sh
