matrix:
  include:
    - language: python
      stage: test_cli
      python: 3.7
      install:
        # START TESTING THE CLI
        - cd cli
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run pytest
        # END TESTING THE CLI
    - language: python
      stage: test_clients
      python: 3.7
      install:
        - pip install ./cli
        - onshape-clients install
      script:
        - onshape-clients test
    - language: python
      stage: deploy
      python: 3.7
      install:
        - nvm install 12
        - pip install ./cli
        - which onshape-clients
        - npm install -g semantic-release
        - npm install -g @semantic-release/exec
      script:
        - semantic-release
stages:
  - deploy
  - test_cli
  - test_clients
before_install:
  - openssl aes-256-cbc -K $encrypted_823a8aeaad18_key -iv $encrypted_823a8aeaad18_iv
    -in secrets.sh.enc -out secrets.sh -d
  - source environment.sh
